name: CI Pipeline (C + Python Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install dependencies (if your project needs specific packages)
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential python3 python3-pip

      # 3. Build the C project with make
      - name: Build C project
        run: make

      # 4. Run Python tests
      - name: Run test script
        run: python3 checker.py
